[build-system]
requires = ["hatchling>=1.4.0", "jupyterlab~=4.0"]
build-backend = "hatchling.build"

[project]
name = "jijzept_ai_agent"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 4",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
version = "0.1.0"
description = "A Jupyter AI extension."
authors = [
    { name = "j-i-k-o", email = "jiko.rogy@gmail.com" },
]
dependencies = ["jupyter_ai"]

[project.optional-dependencies]
test = ["coverage", "pytest", "pytest-asyncio", "pytest-cov"]
dev = ["ruff"]

[project.entry-points."jupyter_ai.model_providers"]
my-provider = "jijzept_ai_agent.my_provider:MyCompletionProvider"

[project.entry-points."jupyter_ai.embeddings_model_providers"]
my-provider = "jijzept_ai_agent.my_provider:MyEmbeddingsProvider"

[project.entry-points."jupyter_ai.chat_handlers"]
test-slash-command = "jijzept_ai_agent.slash_command:TestSlashCommand"

[tool.hatch.build.hooks.version]
path = "jijzept_ai_agent/_version.py"

[tool.check-wheel-contents]
ignore = ["W002"]
